name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare site folder
        run: |
          mkdir -p site
          cp index.html CRAFTROICIP.html site/ || true

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          cd site
          git init
          git add .
          git commit -m "Deploy site to gh-pages"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git master:gh-pages

      - name: Enable GitHub Pages (set source to gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Enabling GitHub Pages for branch gh-pages..."
          curl -s -X PUT -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"source":{"branch":"gh-pages","path":"/"}}' | jq || true
